services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile

    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - 'ldap.proxy:host-gateway'

    ports:
      - '5007:80'
      - '${VITE_PORT:-5180}:${VITE_PORT:-5180}'

    environment:
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      LDAP_DEFAULT_HOSTS: 'ldap.proxy'
      LDAP_DEFAULT_PORT: '3389'

    volumes:
      - '.:/var/www'

    networks:
      - gursoy

networks:
  gursoy:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/16  # LDAP IP'si (172.23) ile asla çakışmaz